// Watch page: stats overlay, similar videos, transcript, sentiment,
// sponsorship scan, thumbnail + frame grabs.

(() => {
  const HR = (window.HR = window.HR || {});
  const el = HR.el;
  const PANEL_ID = 'hr-watch-panel';

  function statsFor(v) {
    return HR.ui.stats([
      { label: 'Views', value: HR.fmt.n(v.views), sub: HR.fmt.full(v.views) },
      {
        label: 'Views / hour',
        value: HR.fmt.n(v.viewsPerHour),
        sub: v.ageHours ? `over ${HR.fmt.n(v.ageHours)}h` : null,
        hint: 'The only fair read on a video too new to have a stable total.',
      },
      {
        label: 'vs channel median',
        value: v.outlier ? HR.fmt.multiplier(v.outlier.multiplier) : '—',
        sub: v.channelMedian ? `median ${HR.fmt.n(v.channelMedian)}` : null,
        tone: v.outlier && v.outlier.multiplier >= 2.5 ? 'good' : null,
      },
      {
        label: 'Engagement',
        value: v.engagementRate == null ? '—' : `${v.engagementRate}%`,
        sub: v.likes ? `${HR.fmt.n(v.likes)} likes` : null,
        hint: 'likes ÷ views. Above ~4% is strong.',
      },
      {
        label: 'Comment rate',
        value: v.commentRate == null ? '—' : `${v.commentRate}%`,
        sub: v.comments ? `${HR.fmt.n(v.comments)} comments` : null,
      },
      {
        label: 'Est. revenue',
        value: HR.fmt.range(v.revenue),
        sub: v.revenue ? `RPM $${v.revenue.rpm}` : null,
      },
      { label: 'Length', value: HR.fmt.duration(v.durationSec) },
      {
        label: 'Ad breaks',
        value: v.adBreaks ?? (v.hasAds ? '1+' : '0'),
        tone: v.hasAds ? 'good' : 'bad',
        hint: 'Read from the player response. Zero can also mean limited ads.',
      },
      { label: 'Published', value: v.publishedAt ? HR.fmt.ago(v.publishedAt) : '—' },
      { label: 'Category', value: v.category || '—', sub: v.country || null },
    ]);
  }

  async function similarPanel(videoId) {
    const modal = HR.ui.modal({ title: 'Similar videos' });
    modal.body.append(HR.ui.skeleton(5, 'Loading…'));
    try {
      const rows = await HR.send('video.similar', { videoId, limit: 24 });
      modal.body.replaceChildren(
        el('div.hr-note', { text: "YouTube's own related graph — the same signal the sidebar uses, unstyled and sortable." }),
        ...rows.map((v) => HR.ui.videoRow(v, { onSave: saveVideo }))
      );
    } catch (err) {
      modal.body.replaceChildren(el('div.hr-error', { text: err.message }));
    }
  }

  async function transcriptPanel(videoId) {
    const modal = HR.ui.modal({ title: 'Transcript' });
    modal.body.append(HR.ui.skeleton(6, 'Fetching captions…'));
    try {
      const t = await HR.send('transcript.get', { videoId });
      const cues = el(
        'div.hr-transcript',
        {},
        t.cues.map((c) =>
          el('div.hr-cue', {}, [
            el('button.hr-cue-at', {
              type: 'button',
              text: c.at,
              onclick: () => {
                const video = HR.qs('video');
                if (video) video.currentTime = c.startMs / 1000;
              },
            }),
            el('span.hr-cue-text', { text: c.text }),
          ])
        )
      );

      modal.body.replaceChildren(
        el('div.hr-note', {
          text: `${t.language}${t.autoGenerated ? ' (auto)' : ''} · ${HR.fmt.full(
            t.wordCount
          )} words · ${t.wordsPerMinute ?? '—'} wpm`,
        }),
        el('div.hr-modal-actions', {}, [
          HR.ui.button('Copy all', () => HR.ui.copy(t.text, 'Transcript copied'), { kind: 'solid' }),
          HR.ui.button('Download .txt', () =>
            HR.send('download.text', { filename: `${videoId}-transcript.txt`, content: t.text })
          ),
          HR.ui.button('Copy with timestamps', () =>
            HR.ui.copy(t.cues.map((c) => `[${c.at}] ${c.text}`).join('\n'), 'Copied')
          ),
        ]),
        cues
      );
    } catch (err) {
      modal.body.replaceChildren(el('div.hr-error', { text: err.message }));
    }
  }

  async function sentimentPanel(videoId) {
    const modal = HR.ui.modal({ title: 'Comment sentiment' });
    modal.body.append(HR.ui.skeleton(5, 'Reading comments…'));
    try {
      const s = await HR.send('sentiment.analyse', { videoId, limit: 120 });
      if (!s.available) {
        modal.body.replaceChildren(
          el('div.hr-empty', { text: 'No comments available (disabled, or none yet).' })
        );
        return;
      }

      const bar = el('div.hr-bar', {}, [
        el('div.hr-bar-seg.hr-good', { style: { width: `${s.positivePct}%` }, title: `positive ${s.positivePct}%` }),
        el('div.hr-bar-seg.hr-neutral', { style: { width: `${s.neutralPct}%` }, title: `neutral ${s.neutralPct}%` }),
        el('div.hr-bar-seg.hr-bad', { style: { width: `${s.negativePct}%` }, title: `negative ${s.negativePct}%` }),
      ]);

      modal.body.replaceChildren(
        el('div.hr-note', {
          text: `${s.sampled} comments sampled · verdict: ${s.verdict} (score ${s.weightedScore}). Lexicon-scored and like-weighted; sarcasm is its blind spot.`,
        }),
        bar,
        HR.ui.stats([
          { label: 'Positive', value: `${s.positivePct}%`, tone: 'good' },
          { label: 'Neutral', value: `${s.neutralPct}%` },
          { label: 'Negative', value: `${s.negativePct}%`, tone: 'bad' },
        ]),
        el('div.hr-subsection', {}, [
          el('div.hr-subsection-title', { text: 'Most-liked comments' }),
          ...s.topComments.map((c) =>
            el('div.hr-comment', {}, [
              el('div.hr-comment-head', {
                text: `${c.author} · ${HR.fmt.n(c.likes)} likes · ${c.label}`,
              }),
              el('div.hr-comment-text', { text: c.text }),
            ])
          ),
        ]),
        s.mostNegative.length
          ? el('div.hr-subsection', {}, [
              el('div.hr-subsection-title', { text: 'Sharpest criticism' }),
              ...s.mostNegative.map((c) =>
                el('div.hr-comment', {}, [
                  el('div.hr-comment-head', { text: `${c.author} · score ${c.score}` }),
                  el('div.hr-comment-text', { text: c.text }),
                ])
              ),
            ])
          : null,
        s.topWords.length
          ? el('div.hr-chips', {}, s.topWords.map(([w, n]) => HR.ui.chip(`${w} ×${n}`, 'muted')))
          : null
      );
    } catch (err) {
      modal.body.replaceChildren(el('div.hr-error', { text: err.message }));
    }
  }

  async function sponsorPanel(videoId) {
    const modal = HR.ui.modal({ title: 'Sponsorship scan' });
    modal.body.append(HR.ui.skeleton(4, 'Scanning transcript + description…'));
    try {
      const s = await HR.send('transcript.sponsorships', { videoId });
      modal.body.replaceChildren(
        el('div.hr-note', {
          text: `${s.sponsored ? 'Sponsorship signals found' : 'No sponsorship signals'} · confidence ${s.confidence}${s.transcriptAvailable ? '' : ' (no transcript — description only)'}`,
        }),
        s.mentions.length
          ? el('div.hr-subsection', {}, [
              el('div.hr-subsection-title', { text: 'Transcript mentions' }),
              ...s.mentions.map((m) =>
                el('div.hr-cue', {}, [
                  el('button.hr-cue-at', {
                    type: 'button',
                    text: m.at,
                    onclick: () => {
                      const video = HR.qs('video');
                      if (video) video.currentTime = m.startMs / 1000;
                    },
                  }),
                  el('span.hr-cue-text', { text: m.text }),
                ])
              ),
            ])
          : null,
        s.affiliateLinks.length
          ? el('div.hr-subsection', {}, [
              el('div.hr-subsection-title', { text: 'Affiliate / tracked links' }),
              ...s.affiliateLinks.map((u) =>
                el('div.hr-link-row', {}, [el('a', { href: u, target: '_blank', rel: 'noopener', text: u })])
              ),
            ])
          : null,
        s.codes.length ? el('div.hr-chips', {}, s.codes.map((c) => HR.ui.chip(c, 'warn'))) : null
      );
    } catch (err) {
      modal.body.replaceChildren(el('div.hr-error', { text: err.message }));
    }
  }

  /** Grab the current frame straight off the <video> element. */
  async function screenshot(videoId) {
    const video = HR.qs('video.html5-main-video') || HR.qs('video');
    if (!video || !video.videoWidth) {
      HR.ui.toast('Player not ready', { kind: 'bad' });
      return;
    }
    try {
      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      const url = canvas.toDataURL('image/png');
      const a = el('a', {
        href: url,
        download: `${videoId}-${Math.round(video.currentTime)}s.png`,
      });
      document.body.append(a);
      a.click();
      a.remove();
      HR.ui.toast('Frame saved', { kind: 'good' });
    } catch (err) {
      // DRM-protected streams taint the canvas; nothing to be done client-side.
      HR.ui.toast(`Frame blocked: ${err.message}`, { kind: 'bad' });
    }
  }

  function saveVideo(v) {
    return HR.send('swipe.save', {
      item: {
        type: v.isShort ? 'short' : 'video',
        ref: v.videoId,
        title: v.title,
        thumbnail: v.thumbnail || `https://i.ytimg.com/vi/${v.videoId}/hqdefault.jpg`,
        url: `https://www.youtube.com/watch?v=${v.videoId}`,
        meta: { views: v.views, outlier: v.outlier?.multiplier ?? null, channelTitle: v.channelTitle },
      },
    }).then(() => HR.ui.toast('Saved to swipe file', { kind: 'good' }));
  }

  async function mount() {
    if (!(await HR.enabled('watchOverlay'))) return;
    const videoId = HR.page.videoId();
    if (!videoId) return;

    const anchor = await HR.waitFor('#secondary-inner, #secondary');
    if (!anchor) return;

    const existing = document.getElementById(PANEL_ID);
    if (existing?.dataset.ref === videoId) return;

    const panel = HR.ui.panel({ id: PANEL_ID, title: 'Hookrate', subtitle: 'video analytics' });
    panel.root.dataset.ref = videoId;
    panel.loading('Reading video…');
    anchor.prepend(panel.root);

    const actions = [
      HR.ui.button('Similar', () => similarPanel(videoId)),
      HR.ui.button('Transcript', () => transcriptPanel(videoId)),
      HR.ui.button('Sentiment', () => sentimentPanel(videoId)),
      HR.ui.button('Sponsors', () => sponsorPanel(videoId)),
      HR.ui.button('Thumb', () =>
        HR.send('download.thumbnail', { videoId })
          .then((r) => HR.ui.toast(`Thumbnail saved (${r.quality})`, { kind: 'good' }))
          .catch((e) => HR.ui.toast(e.message, { kind: 'bad' }))
      ),
      HR.ui.button('Frame', () => screenshot(videoId)),
    ];
    panel.root.querySelector('.hr-panel-actions')?.replaceChildren(...actions);

    try {
      const v = await HR.send('video.stats', { videoId, withChannel: true });
      panel.setBody(
        el('div.hr-panel-badges', {}, [
          v.outlier ? HR.ui.outlier(v.outlier) : null,
          HR.ui.chip(v.hasAds ? 'ads served' : 'no ads seen', v.hasAds ? 'good' : 'warn'),
          v.isShort ? HR.ui.chip('Short', 'muted') : null,
        ]),
        statsFor(v),
        el('div.hr-modal-actions', {}, [
          HR.ui.button('Save to swipe file', () => saveVideo(v), { kind: 'solid' }),
          v.channelId
            ? HR.ui.button('Open channel analytics', () => {
                location.href = `/channel/${v.channelId}`;
              })
            : null,
        ])
      );
    } catch (err) {
      panel.error(err.message);
    }
  }

  HR.features = HR.features || {};
  HR.features.watch = { mount, PANEL_ID, screenshot, saveVideo };
})();
