// Monetization detection.
//
// There is no API field for this. `channels.list` does not expose it, so the
// status has to be inferred. Signal ranking, strongest first:
//
//   adPlacements / playerAds in the player response  -> decisive (ads served)
//   memberships / merch / super-thanks surfaces      -> strong positive
//   YPP eligibility thresholds                       -> eligibility only
//
// Absence of ads on a single video proves nothing: limited-ads ("yellow icon")
// videos, advertiser-unfriendly topics and region gating all suppress
// adPlacements. So sample several recent long-form videos and vote.

import * as yt from '../lib/innertube.js';
import * as cache from '../lib/cache.js';
import { findAll } from '../lib/parse.js';

const SAMPLE_SIZE = 4;
const THROTTLE_MS = 700;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Does this single video carry ad slots? */
async function videoHasAds(videoId) {
  // Path 1: the player endpoint. Cheapest and most explicit.
  try {
    const res = await yt.player(videoId);
    if (res.adPlacements?.length || res.playerAds?.length) return true;
    if (res.adSlots?.length) return true;
    // A valid response with zero ad slots is a real negative, not an error.
    if (res.playabilityStatus?.status === 'OK') return false;
  } catch {
    /* fall through to the HTML path */
  }

  // Path 2: raw watch page. Survives player-endpoint shape changes.
  try {
    const { html } = await yt.page(`/watch?v=${videoId}`);
    return /"adPlacements"|"playerAds"|"adSlotRenderer"/.test(html);
  } catch {
    return null; // unknown, not negative
  }
}

/** Channel-page surfaces that require an active YPP contract. */
function channelSurfaces(html) {
  return {
    memberships: /"sponsorButton"|joinButtonRenderer|"membershipsPortalRenderer"/.test(html),
    merch: /merchandiseShelfRenderer|"shoppingShelf|productListItemRenderer/.test(html),
    superThanks: /superThanks|"paidDigitalGood"/.test(html),
    autoGenerated: /Auto-generated by YouTube|"Art Track"/.test(html),
  };
}

/**
 * YPP eligibility, computed rather than observed.
 * Long-form path: 1,000 subs + 4,000 public watch hours in 12 months.
 * Shorts path:    1,000 subs + 10M valid Shorts views in 90 days.
 */
export function eligibility({ subscribers, videos = [] }) {
  const now = Date.now();
  const YEAR = 365 * 864e5;
  const NINETY = 90 * 864e5;

  let watchHours = 0;
  let longFormCount = 0;
  let shortsInWindow = 0;
  let shortsTotal = 0;
  let shortsDated = 0;

  for (const v of videos) {
    if (!v.views) continue;
    const age = v.publishedAt ? now - v.publishedAt : Infinity;

    if (v.isShort) {
      // Shorts cards expose a view count but no upload date, so the 90-day
      // window is usually unmeasurable from card data. Track the dated subset
      // and the total separately rather than silently reporting zero.
      shortsTotal += v.views;
      if (v.publishedAt) {
        shortsDated++;
        if (age <= NINETY) shortsInWindow += v.views;
      }
      continue;
    }

    longFormCount++;
    if (age > YEAR) continue;
    // Average view duration is unknowable from outside. 45% of run time is a
    // conservative middle for research-grade estimates.
    const seconds = (v.durationSec || 300) * 0.45;
    watchHours += (v.views * seconds) / 3600;
  }

  const windowKnown = shortsDated > 0;
  // Without dates the sampled total spans however long those uploads cover —
  // which for an old channel is far more than 90 days. So this can overstate a
  // real window, and any verdict resting on it must carry lower confidence.
  const shortsForTest = windowKnown ? shortsInWindow : shortsTotal;

  const subsOk = (subscribers || 0) >= 1000;
  return {
    subscribers: subscribers || 0,
    watchHoursEstimate: Math.round(watchHours),
    longFormCount,
    shortsViews90d: windowKnown ? shortsInWindow : null,
    shortsViewsSampled: shortsTotal,
    shortsWindowKnown: windowKnown,
    longFormPath: subsOk && watchHours >= 4000,
    shortsPath: subsOk && shortsForTest >= 10e6,
    eligible: subsOk && (watchHours >= 4000 || shortsForTest >= 10e6),
  };
}

/**
 * Full verdict for a channel.
 * @param {object} input { channelId, channelHtml, videos, subscribers }
 */
export async function detect({ channelId, channelHtml = '', videos = [], subscribers }) {
  return cache.wrap('monetization', channelId, cache.TTL.week, async () => {
    const surfaces = channelSurfaces(channelHtml);
    const elig = eligibility({ subscribers, videos });

    // The 1,000-subscriber floor is a hard YPP rule with no exceptions, so a
    // channel below it is a definitive negative — no need to probe four videos
    // to discover that, and no reason to hedge the answer.
    if (Number.isFinite(subscribers) && subscribers > 0 && subscribers < 1000) {
      return {
        monetized: false,
        confidence: 'high',
        basis: `${subscribers.toLocaleString('en-US')} subscribers — YPP requires 1,000`,
        probes: [],
        surfaces,
        eligibility: elig,
      };
    }

    // Sample recent long-form uploads only. Shorts almost never carry
    // adPlacements, and live/premiere entries skew the vote.
    const sample = videos
      .filter((v) => !v.isShort && (v.durationSec == null || v.durationSec > 65))
      .slice(0, SAMPLE_SIZE);

    const probes = [];
    for (const v of sample) {
      probes.push({ videoId: v.videoId, ads: await videoHasAds(v.videoId) });
      await sleep(THROTTLE_MS);
    }

    const yes = probes.filter((p) => p.ads === true).length;
    const known = probes.filter((p) => p.ads !== null).length;

    // Never assert a negative from an empty or unreadable sample. A channel
    // with no long-form uploads to probe, or one whose probes all failed, is
    // unknown — not unmonetized. Reporting "not monetized" there is the one
    // failure mode that makes the whole verdict untrustworthy.
    if (!known) {
      const surfaced = surfaces.memberships || surfaces.merch || surfaces.superThanks;
      if (surfaced) {
        return {
          monetized: true,
          confidence: 'medium',
          basis:
            'channel exposes memberships/merch/super-thanks (requires YPP); no videos could be sampled',
          probes,
          surfaces,
          eligibility: elig,
        };
      }

      // Shorts-only channel that clears the Shorts path. Ads are unreadable
      // here — Shorts carry no ad slots — but eligibility is not a guess: the
      // subscriber and view thresholds are the published rule, and a channel
      // this far past them is monetized in all but pathological cases.
      // "Unknown" would be throwing away evidence we actually have.
      if (elig.eligible) {
        const dated = elig.shortsWindowKnown;
        const figure = (dated ? elig.shortsViews90d : elig.shortsViewsSampled).toLocaleString(
          'en-US'
        );
        return {
          monetized: true,
          // Without dates the sampled total spans all time, not 90 days, so it
          // cannot prove the window is cleared — only that the channel is in
          // the right order of magnitude. Say so with a lower confidence
          // instead of borrowing certainty the data does not have.
          confidence: dated ? 'medium' : 'low',
          basis:
            `Shorts-only channel: ${elig.subscribers.toLocaleString('en-US')} subs and ` +
            `${figure} Shorts views ` +
            (dated
              ? 'inside the 90-day window clear the Shorts path (1,000 subs + 10M/90d)'
              : 'across sampled Shorts — past 10M, but the 90-day window is unmeasurable without dates. Run "Split valid / invalid" to confirm') +
            ' — inferred from eligibility, since Shorts carry no ad slots',
          probes,
          surfaces,
          eligibility: elig,
        };
      }

      return {
        monetized: null,
        confidence: 'unknown',
        basis: sample.length
          ? `all ${sample.length} sampled videos were unreadable`
          : videos.some((v) => v.isShort)
            ? 'Shorts-only channel below the Shorts thresholds — ad presence cannot be read from Shorts'
            : 'no long-form uploads available to sample',
        probes,
        surfaces,
        eligibility: elig,
      };
    }

    let monetized = false;
    let confidence = 'low';
    let basis = `no ad slots on ${known} sampled video${known === 1 ? '' : 's'}`;

    if (yes > 0) {
      monetized = true;
      confidence = yes >= 2 ? 'high' : 'medium';
      basis = `ad slots present on ${yes}/${known} sampled videos`;
    } else if (surfaces.memberships || surfaces.merch || surfaces.superThanks) {
      monetized = true;
      confidence = 'medium';
      basis = 'channel exposes memberships/merch/super-thanks (requires YPP)';
    } else if (surfaces.autoGenerated) {
      confidence = 'medium';
      basis = 'auto-generated label channel — not a standard YPP contract';
    } else if (elig.eligible) {
      confidence = 'low';
      basis = 'meets YPP thresholds but no ads observed';
    }

    return { monetized, confidence, basis, probes, surfaces, eligibility: elig };
  });
}

/**
 * Split Shorts views into what the 90-day YPP window would count and what it
 * would not.
 *
 * Shorts lockup cards carry a view count but no upload date, so the window is
 * unmeasurable from the channel page alone. Each Short's own player response
 * does carry `publishDate`, so dates are resolved one fetch at a time — which
 * is why this is a separate, opt-in call rather than part of the channel panel.
 *
 * Three buckets, not two. "Unresolved" is its own bucket because folding
 * unknown dates into either side would invent a number.
 *
 * Caveat that cannot be engineered away: YouTube's "valid" also excludes
 * artificial traffic, non-original content and unpublic Shorts. None of that is
 * observable from outside, so the in-window figure is an upper bound.
 */
export async function shortsWindow({ channelId, videos = [], limit = 30 }) {
  const cacheKey = `${channelId || 'adhoc'}:${limit}`;

  return cache.wrap('shorts-window', cacheKey, cache.TTL.day, async () => {
    const now = Date.now();
    const NINETY = 90 * 864e5;

    const shorts = videos.filter((v) => v.isShort && Number.isFinite(v.views));
    const targets = shorts.slice(0, limit);

    const rows = [];
    for (const s of targets) {
      let publishedAt = s.publishedAt || null;

      if (!publishedAt) {
        try {
          const res = await yt.player(s.videoId);
          const micro = res.microformat && res.microformat.playerMicroformatRenderer;
          const iso = micro && (micro.publishDate || micro.uploadDate);
          const parsed = iso ? Date.parse(iso) : NaN;
          if (Number.isFinite(parsed)) publishedAt = parsed;
        } catch {
          /* leave unresolved */
        }
        await sleep(THROTTLE_MS / 2);
      }

      rows.push({
        videoId: s.videoId,
        title: s.title,
        views: s.views,
        publishedAt,
        ageDays: publishedAt ? Math.round((now - publishedAt) / 864e5) : null,
        inWindow: publishedAt ? now - publishedAt <= NINETY : null,
      });
    }

    const bucket = (test) => {
      const picked = rows.filter(test);
      return {
        count: picked.length,
        views: picked.reduce((a, r) => a + r.views, 0),
        videos: picked
          .slice()
          .sort((a, b) => b.views - a.views)
          .slice(0, 10),
      };
    };

    const inWindow = bucket((r) => r.inWindow === true);
    const outWindow = bucket((r) => r.inWindow === false);
    const unresolved = bucket((r) => r.inWindow === null);

    // Shorts beyond the sampled page were never fetched; count them so the
    // total on screen reconciles with the channel's real Shorts output.
    const notSampled = shorts.slice(limit);

    return {
      channelId: channelId || null,
      threshold: 10e6,
      sampled: targets.length,
      totalShortsFound: shorts.length,
      capped: shorts.length > targets.length,
      notSampled: {
        count: notSampled.length,
        views: notSampled.reduce((a, v) => a + v.views, 0),
      },
      inWindow,
      outWindow,
      unresolved,
      countedViews: inWindow.views,
      meetsThreshold: inWindow.views >= 10e6,
      caveat:
        'Upper bound. YouTube also excludes artificial traffic, non-original content and non-public Shorts from "valid" views — none of which is observable from outside.',
    };
  });
}

/** Quick single-video check, used by the watch-page overlay. */
export async function detectVideo(videoId) {
  return cache.wrap('monetization-video', videoId, cache.TTL.day, async () => {
    const ads = await videoHasAds(videoId);
    return { videoId, ads };
  });
}

/** Count how many ad breaks the player declares (mid-roll density). */
export async function adBreaks(videoId) {
  try {
    const res = await yt.player(videoId);
    const slots = findAll(res, 'adSlotMetadata').length;
    return slots || (res.adPlacements || []).length;
  } catch {
    return null;
  }
}
