// Transcripts and captions.
//
// Pulled from the caption tracks the player response already advertises, then
// fetched as json3. No third-party service, no key.

import * as yt from '../lib/innertube.js';
import * as cache from '../lib/cache.js';

function pickTrack(tracks, preferred) {
  if (!tracks?.length) return null;
  const wanted = (preferred || 'en').toLowerCase();
  return (
    tracks.find((t) => t.languageCode?.toLowerCase() === wanted && t.kind !== 'asr') ||
    tracks.find((t) => t.languageCode?.toLowerCase() === wanted) ||
    tracks.find((t) => t.languageCode?.toLowerCase().startsWith(wanted.slice(0, 2))) ||
    tracks[0]
  );
}

function stamp(ms) {
  const total = Math.floor(ms / 1000);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n) => String(n).padStart(2, '0');
  return h ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

/** Available caption languages for a video. */
export async function languages(videoId) {
  const res = await yt.player(videoId);
  const tracks = res.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  return tracks.map((t) => ({
    code: t.languageCode,
    name: t.name?.simpleText || t.name?.runs?.[0]?.text || t.languageCode,
    autoGenerated: t.kind === 'asr',
  }));
}

/**
 * Fetch a transcript as timed cues plus a flat text blob.
 * @returns {{videoId:string, language:string, autoGenerated:boolean,
 *            cues:Array<{startMs:number, durationMs:number, at:string, text:string}>,
 *            text:string, wordCount:number, wordsPerMinute:number|null}}
 */
export async function get(videoId, language = 'en') {
  return cache.wrap('transcript', `${videoId}:${language}`, cache.TTL.week, async () => {
    const res = await yt.player(videoId);
    const tracks = res.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    const track = pickTrack(tracks, language);
    if (!track?.baseUrl) throw new Error('no captions available for this video');

    const url = `${track.baseUrl}&fmt=json3`;
    const raw = await fetch(url, { credentials: 'omit' });
    if (!raw.ok) throw new Error(`captions fetch -> ${raw.status}`);
    const json = await raw.json();

    const cues = (json.events || [])
      .filter((e) => e.segs)
      .map((e) => ({
        startMs: e.tStartMs || 0,
        durationMs: e.dDurationMs || 0,
        at: stamp(e.tStartMs || 0),
        text: e.segs
          .map((s) => s.utf8 || '')
          .join('')
          .replace(/\n+/g, ' ')
          .trim(),
      }))
      .filter((c) => c.text);

    const text = cues.map((c) => c.text).join(' ').replace(/\s+/g, ' ').trim();
    const words = text ? text.split(/\s+/).length : 0;
    const lengthSec = Number(res.videoDetails?.lengthSeconds) || null;

    return {
      videoId,
      language: track.languageCode,
      autoGenerated: track.kind === 'asr',
      cues,
      text,
      wordCount: words,
      wordsPerMinute: lengthSec ? Math.round(words / (lengthSec / 60)) : null,
    };
  });
}

/**
 * Sponsorship / brand-deal detection over a transcript + description.
 * Pattern-based, not a model — cheap, and precise enough that a human can
 * verify each hit from the timestamp.
 */
const SPONSOR_CUES = [
  /thanks? to ([A-Z][\w.-]{2,30}) for sponsoring/i,
  /sponsor(?:ed|ship)? (?:by|of|from) ([A-Z][\w.-]{2,30})/i,
  /this (?:video|episode) is sponsored/i,
  /use (?:my |the )?code ([A-Z0-9]{3,15})/,
  /(\d{1,2})% off/i,
  /(?:link|links) (?:in|below) the description/i,
  /free trial/i,
  /go to ([a-z0-9-]+\.(?:com|io|co|net|org))\/[a-z0-9-]+/i,
];

export async function sponsorships(videoId) {
  const [t, player] = await Promise.all([
    get(videoId).catch(() => null),
    yt.player(videoId).catch(() => null),
  ]);

  const description = player?.videoDetails?.shortDescription || '';
  const hits = [];

  if (t) {
    for (const cue of t.cues) {
      for (const re of SPONSOR_CUES) {
        const m = cue.text.match(re);
        if (m) {
          hits.push({ at: cue.at, startMs: cue.startMs, text: cue.text, matched: m[1] || m[0] });
          break;
        }
      }
    }
  }

  const affiliateLinks = [...description.matchAll(/https?:\/\/[^\s]+/g)]
    .map((m) => m[0])
    .filter((u) =>
      /(ref=|aff|utm_|\/r\/|partner|promo|discount|bit\.ly|geni\.us|amzn\.to)/i.test(u)
    );

  const codes = [...description.matchAll(/\b(?:code|coupon)\s*:?\s*([A-Z0-9]{3,15})\b/g)].map(
    (m) => m[1]
  );

  return {
    videoId,
    sponsored: hits.length > 0 || affiliateLinks.length > 0,
    confidence: hits.length >= 2 ? 'high' : hits.length || affiliateLinks.length ? 'medium' : 'low',
    mentions: hits.slice(0, 12),
    affiliateLinks: [...new Set(affiliateLinks)].slice(0, 20),
    codes: [...new Set(codes)],
    transcriptAvailable: !!t,
  };
}
